#pragma once

#define WIN32_LEAN_AND_MEAN             // Exclude rarely-used stuff from Windows headers
// Windows Header Files
#include <windows.h>
#include <cstdint>

enum WindowedModes : int32_t
{
    WNDMODE_UNK = -1,
    WNDMODE_DEFAULT,
    WNDMODE_MIN = WNDMODE_DEFAULT,
    WNDMODE_BORDERED,
    WNDMODE_BORDERLESS,
    WNDMODE_BORDERLESS_STRETCH,
    WNDMODE_MAX = WNDMODE_BORDERLESS_STRETCH,
    WNDMODE_COUNT
};

enum SteeringAssistType : int32_t
{
	STEERINGASSIST_UNK = -1,
	STEERINGASSIST_DEFAULT,
	STEERINGASSIST_MIN = STEERINGASSIST_DEFAULT,
	STEERINGASSIST_NONE,
	STEERINGASSIST_SPORTS,
	STEERINGASSIST_RACER,
	STEERINGASSIST_MAX = STEERINGASSIST_RACER,
	STEERINGASSIST_NUM,
};

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  reason, LPVOID lpReserved);
